@extends('container.empty')

@section('body')
    <table class="list" width="98%">
        <thead>
        <tr>
            <th>权限名</th>
            <th>拥有状态</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>文章新闻发布权限</td>
            <td>{{$power->addArticle?"✓":""}}</td>
        </tr>
        <tr>
            <td>文章新闻审核权限</td>
            <td>{{$power->passArticle?"✓":""}}</td>
        </tr>
        <tr>
            <td>文章新闻栏目管理权限</td>
            <td>{{$power->Catalogs?"✓":""}}</td>
        </tr>
        <tr>
            <td>通知公告发布权限</td>
            <td>{{$power->addNotice?"✓":""}}</td>
        </tr>
        <tr>
            <td>通知公告审核权限</td>
            <td>{{$power->passNotice?"✓":""}}</td>
        </tr>
        <tr>
            <td>广告管理权限</td>
            <td>{{$power->Advertisement?"✓":""}}</td>
        </tr>
        <tr>
            <td>友情链接管理权限</td>
            <td>{{$power->friendLink?"✓":""}}</td>
        </tr>
        <tr>
            <td>滚动图管理权限</td>
            <td>{{$power->Banner?"✓":""}}</td>
        </tr>
        <tr>
            <td>教师请假添加权限</td>
            <td>{{$power->addTeacherNote?"✓":""}}</td>
        </tr>
        <tr>
            <td>教师请假审核权限</td>
            <td>{{$power->passTeacherNote?"✓":""}}</td>
        </tr>
        <tr>
            <td>学生请假添加权限</td>
            <td>{{$power->addStudentNote?"✓":""}}</td>
        </tr>
        <tr>
            <td>学生请假审核权限</td>
            <td>{{$power->passStudentNote?"✓":""}}</td>
        </tr>
        <tr>
            <td>教学资源上传权限</td>
            <td>{{$power->addResource?"✓":""}}</td>
        </tr>
        <tr>
            <td>教学资源审核权限</td>
            <td>{{$power->passResource?"✓":""}}</td>
        </tr>
        <tr>
            <td>选修课申报权限</td>
            <td>{{$power->addCourse?"✓":""}}</td>
        </tr>
        <tr>
            <td>选修课审核权限</td>
            <td>{{$power->passCourse?"✓":""}}</td>
        </tr>
        <tr>
            <td>资产申请权限</td>
            <td>{{$power->Application?"✓":""}}</td>
        </tr>
        <tr>
            <td>仓库管理审核权限</td>
            <td>{{$power->Asset?"✓":""}}</td>
        </tr>
        <tr>
            <td>学生管理</td>
            <td>{{$power->Student?"✓":""}}</td>
        </tr>
        <tr>
            <td>专业班级管理</td>
            <td>{{$power->Class?"✓":""}}</td>
        </tr>
        <tr>
            <td>教师管理</td>
            <td>{{$power->Teacher?"✓":""}}</td>
        </tr>
        <tr>
            <td>教师权限</td>
            <td>{{$power->Power?"✓":""}}</td>
        </tr>
        </tbody>
    </table>
@endsection